name: Unit & Component Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  tests:
    name: Run unit tests and CT tests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    env:
      VITE_APP_GIT_TAG: ${{github.ref}}
      VITE_APP_GIT_SHA: ${{github.sha}}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint (show only errors)
        run: pnpm lint --quiet
      - name: Check exports
        run: pnpm check-exports-ci
      - name: Test
        run: pnpm test
      - name: Tests storybook
        run: pnpm test:storybook
      # - name: Build Storybook
      #   run: pnpm build-storybook --quiet
      # - name: Install Playwright browsers (ensuring compatibility)
      #   run: |
      #     # Install via the project's playwright version to ensure compatibility
      #     pnpm exec playwright install chromium
      #     # Also install system dependencies
      #     pnpm exec playwright install-deps chromium
      # - name: Run Storybook tests
      #   run: pnpx start-server-and-test 'pnpx http-server storybook-static --port 6006 --silent' http://localhost:6006 'pnpm test-storybook'
      - name: Build
        run: pnpm build
